name: Super Spor Botu Guncelle

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
  # Eğer her push'ta çalışmasını istemiyorsanız bu satırı kaldırın.
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu Cek
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Kutuphaneleri Yukle
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Botu Calistir
        run: python main.py

      - name: Kaydet ve Yukle
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"

          git add Canli_Spor_Hepsi.m3u

          # Değişiklik yoksa çık
          git diff --cached --quiet && exit 0

          git commit -m "Tum Siteler Guncellendi: $(date)"

          # Uzak depodaki son değişiklikleri al
          git pull --rebase origin main

          # Push et
          git push origin main
